title: Peekmo 
description: "Un p'tit blog qui traite de mouuuuultes sujets"
author:
  name: Peekmo 
  email: XXXX 
  url:
  gravatar: XXXX 
  description: "Moi."
blog:
  route: ''
metadata:
    description: "Un p'tit blog qui traite de mouuuuultes sujets"
taxonomies: [category,tag,month]

# Show calendar in sidebar
calendar: false 

languages:
  translations: true
  supported:
    - fr

menu:

# Copyright
copyright:
  left: <span>Copyright</span> © 2015 <a href="http://andersnoren.se/themes/lingonberry/" title="Lingonberry">Lingonberry</a>, Ported By <a href="http://www.getgrav.org" rel="dofollow" target="_blank" title="Grav">Grav Team</a>
  right: <span>Theme by <a href="http://www.andersnoren.se">Anders Noren</a> — </span><a title="To the top" class="tothetop">Up ↑</a>
